### ISSUE TITLE
🗒todo list

### ISSUE THREAD

**Issue by qkrdmstlr3** [Start-Off/StartOff-front#36]
- [x] 로그인 창에서 에러 발생후 회원가입 갔다 돌아오면 이전 에러 모달이 한번 더 뜸
- [x] mock-data파일 정리
- [x] api이름 정리
- [ ] memo사용으로 효율성 개선
- [ ] pagination 컴포넌트 버튼부분 분리해보기

- [x] SkillList의 스킬목록 molecule로 빼기
- [ ] markdown, 완료 여부 molecule로 빼기
